"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# За nginx приложение видит обычный http, поэтому абсолютные URL (в том числе
# картинки категорий в выдаче API) строились как http://api.airbagad.com/…
# На HTTPS-странице это смешанный контент, а next/image в конфиге фронта
# разрешает только https и отвечает 400. Заголовок ставит nginx, а порт 8000
# слушает только 127.0.0.1 — подделать его снаружи нельзя.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
load_dotenv(dotenv_path=BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-#!oj+v1jh^n6i26xq@*ar6pqm_nlotd15tyfhh7&_90xx0t@1$",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "True") == "True"

# Use for local development. Used for static files
LOCAL = os.getenv("LOCAL", "True") == "True"

# Used for Webhook URL - current backend project IP or domain
DOMAIN = os.getenv("DOMAIN")

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS").split(",")

# Remonline  settings
REMONLINE_API_KEY = os.getenv("REMONLINE_API_KEY")
REMONLINE_ORDER_TYPE_ID = os.getenv("REMONLINE_ORDER_TYPE_ID")
REMONLINE_BRANCH_PROD_ID = os.getenv("REMONLINE_BRANCH_PROD_ID")
REMONLINE_TOGETHERBUY_CUSTOM_FIELD_ID = os.getenv(
    "REMONLINE_TOGETHERBUY_CUSTOM_FIELD_ID"
)
PRICE_ID_PROD = os.getenv("PRICE_ID_PROD")
BONUS_ID = os.getenv("BONUS_ID")
# Статусы заказа в RemOnline. Держим идентификаторы в настройках, а не в коде:
# они привязаны к конкретному аккаунту CRM и в тестах подменяются.
#
# DELETE_ORDER_STATUS_ID — историческое имя, на проде переменная уже задана.
# Оставлено как источник значения по умолчанию для «Видалити», чтобы выкат не
# требовал одновременной правки .env.
DELETE_ORDER_STATUS_ID = os.getenv("DELETE_ORDER_STATUS_ID")

# «Видалити» — исходные карточки после объединения заказов.
REMONLINE_STATUS_DELETE = os.getenv("REMONLINE_STATUS_DELETE", DELETE_ORDER_STATUS_ID)
# «Відмова» — клиент отказался от заказа. Отличается от «Видалити»: отказ
# клиента и технический мусор не должны выглядеть в отчётности одинаково.
REMONLINE_STATUS_DROPPED = os.getenv("REMONLINE_STATUS_DROPPED")
# «Новий» — обычный рабочий статус.
REMONLINE_STATUS_NEW = os.getenv("REMONLINE_STATUS_NEW")
# «Оплата по реквізитам» — ждём подтверждения оплаты администратором.
REMONLINE_STATUS_BANK_TRANSFER = os.getenv("REMONLINE_STATUS_BANK_TRANSFER")

# «Відправлений» и «Закрито» здесь нет намеренно: продвижение заказа по цепочке
# ведёт менеджер, система в это не вмешивается (05.09.2026, решение владельца).
# Автоматика двигает статус только там, где сама и создала состояние: завела
# карточку по реквизитам и сняла эту пометку после оплаты, отменила, объединила.
_CATEGORIES_WHITELIST_IDS_RAW = os.getenv("CATEGORIES_WHITELIST_IDS", "")
CATEGORIES_WHITELIST_IDS = [
    int(t)
    for t in [x.strip() for x in _CATEGORIES_WHITELIST_IDS_RAW.split(",")]
    if t.strip().isdigit()
]

# Monobank settings
MONOBANK_TOKEN = os.getenv("MONOBANK_TOKEN") #https://web.monobank.ua/ or getting your test token from https://api.monobank.ua/
MONOBANK_WEBHOOK_URL_PATH = "monobank/webhook/payment-events/" # Webhook URL path for monobank payment events
MONOBANK_WEBHOOK_KEY = os.getenv("MONOBANK_WEBHOOK_KEY")

# Per-mode Monobank credentials. Активный режим выбирается в БД
# (payments.PaymentSettings), а токены берутся отсюда. Fallback на общие
# MONOBANK_TOKEN/MONOBANK_WEBHOOK_KEY — для обратной совместимости.
MONOBANK_TOKEN_TEST = os.getenv("MONOBANK_TOKEN_TEST", MONOBANK_TOKEN)
MONOBANK_TOKEN_PROD = os.getenv("MONOBANK_TOKEN_PROD", MONOBANK_TOKEN)
MONOBANK_WEBHOOK_KEY_TEST = os.getenv("MONOBANK_WEBHOOK_KEY_TEST", MONOBANK_WEBHOOK_KEY)
MONOBANK_WEBHOOK_KEY_PROD = os.getenv("MONOBANK_WEBHOOK_KEY_PROD", MONOBANK_WEBHOOK_KEY)

# Google Pay gatewayMerchantId — не секрет, отдаётся фронту через /payments/config/
# по активному режиму. Раньше жил только в NEXT_PUBLIC_* и вшивался в бандл на
# этапе сборки, поэтому переключение режима его не меняло.
GOOGLE_PAY_MERCHANT_ID = os.getenv("GOOGLE_PAY_MERCHANT_ID")
GOOGLE_PAY_MERCHANT_ID_TEST = os.getenv("GOOGLE_PAY_MERCHANT_ID_TEST", GOOGLE_PAY_MERCHANT_ID)
GOOGLE_PAY_MERCHANT_ID_PROD = os.getenv("GOOGLE_PAY_MERCHANT_ID_PROD", GOOGLE_PAY_MERCHANT_ID)

# Celery settings
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://redis:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://redis:6379/1")

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": os.getenv("REDIS_URL", "redis://redis:6379/2"),
    }
}

# Email: Brevo, отправка от noreply@airbagad.com. Своего почтового сервера у
# домена нет, поэтому письма идут через Brevo; домен подтверждён по DKIM
# (SPF не нужен — Return-Path на домене Brevo).
#
# По умолчанию — HTTP API (core.mail.brevo), а не SMTP: провайдеры и облака
# часто режут исходящие почтовые порты (на машине разработчика закрыты и 25,
# и 587), а API ходит обычным HTTPS на 443. Чтобы вернуться на SMTP, достаточно
# выставить EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend в .env —
# настройки EMAIL_HOST/PORT ниже остаются рабочими.
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "core.mail.brevo.BrevoAPIEmailBackend")
BREVO_API_KEY = os.getenv("BREVO_API_KEY", "")
BREVO_API_URL = os.getenv("BREVO_API_URL", "https://api.brevo.com/v3/smtp/email")
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp-relay.brevo.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "False") == "True"
# Логин вида 9xxxxx@smtp-brevo.com и SMTP key из панели: SMTP & API -> SMTP.
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
# Без таймаута зависший коннект к SMTP держит воркер gunicorn бесконечно.
EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", "10"))
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER or "noreply@airbagad.com")
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Публичный адрес фронтенда — из него строится ссылка сброса пароля.
# DOMAIN для этого не годится: он указывает на API (см. payments/serializers.py).
# Берём ТОЛЬКО отсюда, никогда из заголовков запроса — иначе host-header injection.
FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:3000").rstrip("/")
FRONTEND_LOCALES = ("uk", "ru", "en")
FRONTEND_DEFAULT_LOCALE = "uk"

# Время жизни ссылки сброса пароля, секунды (Django по умолчанию даёт 3 суток).
PASSWORD_RESET_TIMEOUT = int(os.getenv("PASSWORD_RESET_TIMEOUT", "3600"))
# Ссылка подтверждения почты живёт дольше: её открывают не «прямо сейчас»,
# а когда дойдут руки до почтового ящика. По умолчанию 3 суток.
EMAIL_CONFIRMATION_TIMEOUT = int(os.getenv("EMAIL_CONFIRMATION_TIMEOUT", "259200"))
# False — слать письмо синхронно, минуя Celery (удобно в тестах и в dev без брокера).
PASSWORD_RESET_EMAIL_ASYNC = os.getenv("PASSWORD_RESET_EMAIL_ASYNC", "True") == "True"

# DRF pagination and filter settings
REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "core.pagination.CustomLimitOffsetPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
        "core.filters.backend.UniversalFieldFilterBackend",
        "rest_framework.filters.OrderingFilter",
    ),
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "core.authentication.ApiKeyAuthentication",
        # Не штатный JWTAuthentication: наш отбраковывает токены, выданные до
        # смены пароля (см. core/authentication.py).
        "core.authentication.PasswordAwareJWTAuthentication",
    ),
    # DEFAULT_THROTTLE_CLASSES намеренно не задаём — иначе лимиты молча накроют
    # все существующие вьюхи. Троттлинг включается точечно, на публичных вьюхах.
    #
    # Лимиты по адресу почты жёсткие (это защита конкретного ящика от заваливания
    # письмами), а по IP — намеренно свободнее: за одним NAT сидит целый офис или
    # мобильный оператор, и строгий лимит там блокировал бы добросовестных людей.
    "DEFAULT_THROTTLE_RATES": {
        "password_reset_email": os.getenv("THROTTLE_PASSWORD_RESET_EMAIL", "3/day"),
        "password_reset": os.getenv("THROTTLE_PASSWORD_RESET_IP", "20/day"),
        "password_reset_confirm": os.getenv("THROTTLE_PASSWORD_RESET_CONFIRM", "10/hour"),
        "email_confirmation_email": os.getenv("THROTTLE_EMAIL_CONFIRMATION_EMAIL", "3/day"),
        "email_confirmation": os.getenv("THROTTLE_EMAIL_CONFIRMATION_IP", "20/day"),
        # Забор аккаунта из старой системы. Мягче почтовых лимитов: за одним
        # NAT сидит целый офис, а перебор кодов и без того безнадёжен —
        # 24 случайных байта. Но совсем без потолка публичный эндпоинт,
        # отдающий подсказку по телефону, оставлять нельзя.
        "account_claim": os.getenv("THROTTLE_ACCOUNT_CLAIM_IP", "60/hour"),
    },
}
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=2),
    # Dedicated JWT signing key (>=32 bytes recommended for HS256). Falls back
    # to SECRET_KEY if not set. Rotating this invalidates all existing tokens.
    "SIGNING_KEY": os.getenv("JWT_SIGNING_KEY", SECRET_KEY),
}
SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": 'JWT Authorization header using the Bearer scheme. Example: "Bearer {token}"',
        }
    },
    "USE_SESSION_AUTH": False,
}

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "django_filters",
    "drf_yasg",
    "core.apps.CoreConfig",
    "payments.apps.PaymentsConfig",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    }
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Кастомная модель пользователя
AUTH_USER_MODEL = "core.Client"


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",  # Можно поставить 'DEBUG' для подробностей
    },
}

# CORS settings
# Список хардкодился и не содержал самого сайта — держалось всё на
# CORS_ALLOW_ALL_ORIGINS = DEBUG ниже. Выключить DEBUG на бою было нельзя:
# фронт немедленно отваливался по CORS. Теперь боевой домен в списке всегда, а
# дополнительные (ngrok при отладке) добавляются через CORS_EXTRA_ORIGINS.
def _origins_from_env(name):
    raw = os.getenv(name, "")
    return [item.strip().rstrip("/") for item in raw.split(",") if item.strip()]


_SITE_ORIGINS = [
    "https://airbagad.com",
    "https://www.airbagad.com",
    "https://api.airbagad.com",
]
_DEV_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

CORS_ALLOWED_ORIGINS = _SITE_ORIGINS + _DEV_ORIGINS + _origins_from_env(
    "CORS_EXTRA_ORIGINS"
)

# Trusted origins for CSRF
CSRF_TRUSTED_ORIGINS = list(CORS_ALLOWED_ORIGINS)

CORS_ALLOW_CREDENTIALS = True
# Открыто всем только при DEBUG. На бою DEBUG обязан быть False — и теперь это
# ничего не ломает, потому что airbagad.com есть в CORS_ALLOWED_ORIGINS.
CORS_ALLOW_ALL_ORIGINS = DEBUG

# Allow specific headers that might be needed for your API
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "ngrok-skip-browser-warning",
]
