# Generated by Django 5.2.4 on 2025-07-15 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotVisitor",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("telegram_id", models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("procent", models.IntegerField()),
                ("month_payment", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ShoppingCart",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("telegram_id", models.BigIntegerField()),
                ("good_id", models.BigIntegerField()),
                ("count", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("text", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("id_remonline", models.BigIntegerField()),
                ("telegram_id", models.BigIntegerField()),
                ("name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("login", models.CharField(max_length=128, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to.",
                        related_name="client_set",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="client_set",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClientUpdate",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=32)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="core.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("remonline_order_id", models.BigIntegerField(blank=True, null=True)),
                ("telegram_id", models.BigIntegerField()),
                ("goods_list", models.TextField()),
                ("name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("prepayment", models.BooleanField(default=False)),
                ("phone", models.CharField(max_length=20)),
                ("nova_post_address", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("is_paid", models.BooleanField(default=False)),
                ("ttn", models.TextField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("date", models.DateTimeField()),
                ("remember_count", models.IntegerField(default=0)),
                ("branch_remember_count", models.IntegerField(default=0)),
                ("in_branch_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="core.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderUpdate",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=32)),
                ("details", models.TextField(blank=True, null=True)),
                ("order", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "order_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_updates",
                        to="core.order",
                    ),
                ),
            ],
        ),
    ]
