# Generated by Django 5.2.4 on 2025-07-15 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_remonline', models.BigIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('parent_id', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_remonline', models.BigIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('images', models.JSONField()),
                ('price', models.IntegerField()),
                ('residue', models.IntegerField()),
                ('code', models.IntegerField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods', to='core.goodcategory')),
            ],
        ),
    ]
