# Generated by Django 5.2.4 on 2025-07-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cart_cartitem_orderitem_delete_shoppingcart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.AlterField(
            model_name='good',
            name='images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
