# Generated by Django 5.2.4 on 2025-07-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_orderitem_price_alter_good_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='code',
            field=models.CharField(max_length=32),
        ),
    ]
