# Generated by Django 5.2.4 on 2025-07-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_good_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id_remonline',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
