# Generated by Django 5.2.4 on 2025-07-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_client_id_remonline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
