# Generated by Django 5.2.4 on 2025-08-08 21:11

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_client_email_alter_client_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='procent',
        ),
        migrations.AddField(
            model_name='discount',
            name='percentage',
            field=core.models.CustomPercentageField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
