# Generated by Django 5.2.4 on 2025-08-14 19:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_client_nova_post_address"),
    ]

    operations = [
        # Replace bad RenameField(count -> quantity) with AddField(quantity)
        migrations.AddField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name="good",
            name="price",
        ),
        migrations.AddField(
            model_name="cart",
            name="currency",
            field=models.CharField(default="UAH", max_length=3),
        ),
        migrations.AddField(
            model_name="clientupdate",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="good",
            name="currency",
            field=models.CharField(default="UAH", max_length=3),
        ),
        migrations.AddField(
            model_name="good",
            name="price_minor",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_percent",
            field=core.models.CustomPercentageField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_total_minor",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="grand_total_minor",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="subtotal_minor",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="category_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="code",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="currency",
            field=models.CharField(default="UAH", max_length=3),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="discount_minor",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="discount_percent",
            field=core.models.CustomPercentageField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="good_external_id",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="id_remonline",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="line_subtotal_minor",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="line_total_minor",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="original_price_minor",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="title",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="unit_price_minor",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orderupdate",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="client",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="login",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="telegram_id",
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="discount",
            name="month_payment",
            field=models.BigIntegerField(
                help_text="Total payments for the month in minor units"
            ),
        ),
        migrations.AlterField(
            model_name="good",
            name="code",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="good",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="good",
            name="residue",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="order",
            name="remonline_order_id",
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="telegram_id",
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="good",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.good",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["date"], name="core_order_date_3a020a_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["client", "date"], name="core_order_client__c5d86a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(fields=["order"], name="core_orderi_order_i_b7b8d3_idx"),
        ),
    ]
