# Generated by Django 5.2.4 on 2025-08-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_count_orderitem_quantity_remove_good_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='count',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='good_external_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id_remonline',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
