# Generated by Django 5.2.4 on 2025-08-16 10:20

from django.db import migrations

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_remove_orderitem_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="discount_percent",
            field=core.models.CustomPercentageField(default=0, max_digits=5),
        ),
    ]
