# Generated by Django 5.2.4 on 2025-08-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_client_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='together_buy',
            field=models.JSONField(blank=True, default=list, help_text='Optional list of related Good IDs (bigint) often bought together', null=True),
        ),
    ]
