# Generated by Django 5.2.4 on 2025-08-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_good_together_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
    ]
