# Generated by Django 5.2.4 on 2025-08-24 19:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_client_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderupdate',
            name='order_ref',
        ),
        migrations.CreateModel(
            name='ClientEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('MERGED', 'Merged'), ('CREATED_ADMIN_MESSAGE', 'Created Admin Message'), ('CREATED_CLIENT_MESSAGE', 'Created Client Message'), ('FINISHED', 'Finished'), ('TTN_UPDATED', 'TTN Updated'), ('IN_BRANCH', 'In Branch')], max_length=32)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_events', to='core.order')),
            ],
        ),
        migrations.DeleteModel(
            name='ClientUpdate',
        ),
        migrations.DeleteModel(
            name='OrderUpdate',
        ),
    ]
