# Generated by Django 5.2.4 on 2026-03-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_monobankinvoiceevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
