# Generated by Django 5.2.4 on 2026-03-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_failure_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='failure_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
