# Generated by Django 5.2.4 on 2026-08-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_paymentsettings'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='monobankinvoiceevent',
            constraint=models.UniqueConstraint(fields=('invoice_id', 'status', 'modified_date'), name='uniq_monobank_invoice_event'),
        ),
    ]
