# Generated by Django 5.2.4 on 2026-08-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_monobankinvoiceevent_uniq_monobank_invoice_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
