# Generated by Django 5.2.4 on 2025-08-25 09:41

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotVisitor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('telegram_id', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('percentage', core.models.CustomPercentageField(decimal_places=2, max_digits=5)),
                ('month_payment', models.BigIntegerField(help_text='Total payments for the month in minor units')),
            ],
        ),
        migrations.CreateModel(
            name='GoodCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_remonline', models.BigIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('parent_id', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_remonline', models.BigIntegerField(blank=True, null=True)),
                ('telegram_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('login', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nova_post_address', models.TextField(blank=True, null=True)),
                ('discount_percent', core.models.CustomPercentageField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_guest', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='client_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='client_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('currency', models.CharField(default='UAH', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_remonline', models.BigIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, null=True)),
                ('together_buy', models.JSONField(blank=True, default=list, help_text='Optional list of related Good IDs (bigint) often bought together', null=True)),
                ('price_minor', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='UAH', max_length=3)),
                ('residue', models.IntegerField(default=0)),
                ('code', models.CharField(blank=True, max_length=32, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods', to='core.goodcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('remonline_order_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('telegram_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('nova_post_address', models.TextField()),
                ('prepayment', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('ttn', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('discount_percent', core.models.CustomPercentageField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('subtotal_minor', models.BigIntegerField(default=0)),
                ('discount_total_minor', models.BigIntegerField(default=0)),
                ('grand_total_minor', models.BigIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('remember_count', models.IntegerField(default=0)),
                ('branch_remember_count', models.IntegerField(default=0)),
                ('in_branch_datetime', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('MERGED', 'Merged'), ('CREATED_ADMIN_MESSAGE', 'Created Admin Message'), ('CREATED_CLIENT_MESSAGE', 'Created Client Message'), ('FINISHED', 'Finished'), ('TTN_UPDATED', 'TTN Updated'), ('IN_BRANCH', 'In Branch')], max_length=32)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_events', to='core.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_external_id', models.BigIntegerField()),
                ('id_remonline', models.BigIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=32, null=True)),
                ('category_id', models.BigIntegerField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('currency', models.CharField(default='UAH', max_length=3)),
                ('original_price_minor', models.BigIntegerField(default=0)),
                ('discount_percent', core.models.CustomPercentageField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_minor', models.BigIntegerField(default=0)),
                ('unit_price_minor', models.BigIntegerField(default=0)),
                ('line_subtotal_minor', models.BigIntegerField(default=0)),
                ('line_total_minor', models.BigIntegerField(default=0)),
                ('good', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.good')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.cart')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.good')),
            ],
            options={
                'unique_together': {('cart', 'good')},
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['date'], name='core_order_date_3a020a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client', 'date'], name='core_order_client__c5d86a_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='core_orderi_order_i_b7b8d3_idx'),
        ),
    ]
