# Generated by Django 5.2.4 on 2025-09-25 17:27

import secrets

from django.db import migrations


def generate_api_keys(apps, schema_editor):
    Client = apps.get_model('core', 'Client')
    for client in Client.objects.all():
        client.api_key = secrets.token_urlsafe(32)
        client.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_client_api_key'),
    ]

    operations = [
        migrations.RunPython(generate_api_keys, reverse_code=migrations.RunPython.noop),
    ]
