# Generated by Django 5.2.4 on 2025-10-23 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250925_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='discount_percent',
        ),
    ]
