# Generated by Django 5.2.4 on 2026-01-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_client_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
