# Generated by Django 5.2.4 on 2026-03-05 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_goodcategory_image'),
        ('core', '0005_order_sync_status_and_event_types'),
    ]

    operations = [
    ]
