# Generated by Django 5.2.4 on 2026-06-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20260305_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bank_transfer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_document',
            field=models.FileField(blank=True, null=True, upload_to='payment_docs/'),
        ),
    ]
