# Generated by Django 5.2.4 on 2026-06-04 02:13

from django.db import migrations, models


def seed_bank_details(apps, schema_editor):
    BankDetails = apps.get_model("core", "BankDetails")
    if not BankDetails.objects.exists():
        BankDetails.objects.create(
            full_name="Гекало Дмитро",
            card_number="4035 2000 4221 9094",
            account_number="",
            edrpou="",
            payment_purpose="",
            is_active=True,
        )


def unseed_bank_details(apps, schema_editor):
    apps.get_model("core", "BankDetails").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order_bank_transfer_and_payment_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('card_number', models.CharField(blank=True, default='', max_length=64)),
                ('account_number', models.CharField(blank=True, default='', max_length=64)),
                ('edrpou', models.CharField(blank=True, default='', max_length=32)),
                ('payment_purpose', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bank Details',
                'verbose_name_plural': 'Bank Details',
            },
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='type',
            field=models.CharField(choices=[('MERGED', 'Merged'), ('CREATED_ADMIN_MESSAGE', 'Created Admin Message'), ('CREATED_CLIENT_MESSAGE', 'Created Client Message'), ('FINISHED', 'Finished'), ('TTN_UPDATED', 'TTN Updated'), ('IN_BRANCH', 'In Branch'), ('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('REMONLINE_CREATED', 'Remonline Created'), ('PAYMENT_TYPE_CHANGED', 'Payment Type Changed'), ('PAYMENT_DOC_UPLOADED', 'Payment Document Uploaded')], max_length=32),
        ),
        migrations.RunPython(seed_bank_details, unseed_bank_details),
    ]
