# Generated by Django 5.2.4 on 2026-06-04 19:57

from django.db import migrations, models

from core.text_utils import transliterate_slug


def backfill_slugs(apps, schema_editor):
    """Populate slug for existing Good / GoodCategory rows from their titles."""
    for model_name in ("Good", "GoodCategory"):
        Model = apps.get_model("core", model_name)
        to_update = []
        for obj in Model.objects.filter(slug="").only("id", "title"):
            obj.slug = transliterate_slug(obj.title or "")
            to_update.append(obj)
        if to_update:
            Model.objects.bulk_update(to_update, ["slug"], batch_size=200)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_bank_details_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='good',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='good',
            name='slug',
            field=models.SlugField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='goodcategory',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goodcategory',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='goodcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=280),
        ),
        migrations.RunPython(backfill_slugs, noop),
    ]
