# Generated by Django 5.2.4 on 2026-08-15 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_backfill_order_totals'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.CharField(blank=True, choices=[('changed_mind', 'Changed mind'), ('found_cheaper', 'Found cheaper'), ('wrong_items', 'Wrong items'), ('delivery_too_long', 'Delivery too long'), ('duplicate', 'Duplicate order'), ('payment_failed', 'Payment failed'), ('other', 'Other'), ('no_contact', 'No contact with client'), ('out_of_stock', 'Out of stock'), ('removed_in_remonline', 'Removed in Remonline')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancel_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancel_state',
            field=models.CharField(blank=True, choices=[('', 'Not canceled'), ('requested', 'Cancellation requested'), ('canceled', 'Canceled'), ('rejected', 'Cancellation rejected')], db_index=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='order',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='canceled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canceled_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_state',
            field=models.CharField(blank=True, choices=[('', 'No refund'), ('pending', 'Refund in progress'), ('done', 'Refunded'), ('manual', 'Refunded manually'), ('failed', 'Refund failed')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='type',
            field=models.CharField(choices=[('MERGED', 'Merged'), ('CREATED_ADMIN_MESSAGE', 'Created Admin Message'), ('CREATED_CLIENT_MESSAGE', 'Created Client Message'), ('FINISHED', 'Finished'), ('TTN_UPDATED', 'TTN Updated'), ('IN_BRANCH', 'In Branch'), ('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('REMONLINE_CREATED', 'Remonline Created'), ('PAYMENT_TYPE_CHANGED', 'Payment Type Changed'), ('PAYMENT_DOC_UPLOADED', 'Payment Document Uploaded'), ('CANCEL_REQUESTED', 'Cancellation Requested'), ('CANCELED', 'Canceled'), ('CANCEL_REJECTED', 'Cancellation Rejected'), ('REFUNDED', 'Refunded')], max_length=32),
        ),
    ]
