# Generated by Django 5.2.4 on 2026-08-17 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_client_email_confirmed'),
        ('core', '0011_order_cancel_comment_order_cancel_reason_and_more'),
    ]

    operations = [
    ]
