# Generated by Django 5.2.4 on 2026-09-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_accountclaimcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cancel_reason',
            field=models.CharField(blank=True, choices=[('changed_mind', 'Changed mind'), ('found_cheaper', 'Found cheaper'), ('wrong_items', 'Wrong items'), ('delivery_too_long', 'Delivery too long'), ('duplicate', 'Duplicate order'), ('payment_failed', 'Payment failed'), ('other', 'Other'), ('no_contact', 'No contact with client'), ('out_of_stock', 'Out of stock'), ('removed_in_remonline', 'Removed in Remonline'), ('merged', 'Merged into another order')], max_length=32, null=True),
        ),
    ]
