# Generated by Django 5.2.4 on 2026-09-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_bank_transfer_orders_are_prepaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_draft',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
