# Generated by Django 5.2.4 on 2026-09-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_order_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='remonline_sync_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SYNCED', 'Synced'), ('FAILED', 'Failed')], default='PENDING', max_length=16),
        ),
    ]
