# Generated by Django 5.2.4 on 2026-09-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_order_remonline_sync_attempts_alter_orderevent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='search_title',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
