# Generated by Django 5.2.4 on 2026-09-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_fill_search_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='np_notified_status',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='type',
            field=models.CharField(choices=[('MERGED', 'Merged'), ('CREATED_ADMIN_MESSAGE', 'Created Admin Message'), ('CREATED_CLIENT_MESSAGE', 'Created Client Message'), ('FINISHED', 'Finished'), ('TTN_UPDATED', 'TTN Updated'), ('IN_BRANCH', 'In Branch'), ('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('REMONLINE_CREATED', 'Remonline Created'), ('PAYMENT_TYPE_CHANGED', 'Payment Type Changed'), ('PAYMENT_DOC_UPLOADED', 'Payment Document Uploaded'), ('CANCEL_REQUESTED', 'Cancellation Requested'), ('CANCELED', 'Canceled'), ('CANCEL_REJECTED', 'Cancellation Rejected'), ('REFUNDED', 'Refunded'), ('REMONLINE_SYNC_FAILED', 'Remonline Sync Failed'), ('DELIVERY_RETURNED', 'Delivery Returned'), ('DELIVERY_FAILED', 'Delivery Failed'), ('PARCEL_DESTROYED', 'Parcel Destroyed')], max_length=32),
        ),
    ]
